name: Create Directory & Show Hostname

on:
  push:
    branches:
      - main  # Jab 'main' branch pe push ho, tab chale

jobs:
  setup:
    runs-on: self-hosted  # EC2 self-hosted runner pe chalega

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create 'hamza' Directory
        run: |
            mkdir -p ~/hamza  
            cd ~/hamza
            touch linux.txt

      - name: Show Server Hostname
        run: hostname
