name: myfirst_action

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: make directory
        run: |
          mkdir hamza
          cd hamza
          touch hamza.text